project:
  type: default
  output-dir: _output

bibliography: ../references.bib

format:
  html:
    toc: true
    number-sections: true
    code-fold: true

  pdf:
    toc: true
    number-sections: true

execute:
  echo: true
  warning: false
  message: false